# Generated by Django 4.2.9 on 2024-02-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('class_name', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=10)),
                ('blood_group', models.CharField(max_length=5)),
                ('father_name', models.CharField(max_length=100)),
                ('caste', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('mother_name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=50)),
                ('first_language', models.CharField(max_length=50)),
                ('medium_of_language', models.CharField(max_length=50)),
                ('emis_no', models.CharField(max_length=20)),
                ('admission_no', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
            ],
        ),
    ]
