# Generated by Django 4.2.9 on 2024-02-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_studentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='roll_number',
            field=models.IntegerField(null=True),
        ),
    ]
