# Generated by Django 4.2.9 on 2024-02-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_studentdetails_category_studentdetails_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='blood_group',
            field=models.CharField(max_length=20),
        ),
    ]
