# Generated by Django 4.2.9 on 2024-02-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0003_staffdetails_designation_staffdetails_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='staff_images/'),
        ),
    ]
