# Generated by Django 4.2.9 on 2024-02-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0004_staffdetails_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffdetails',
            name='join_data',
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='join_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='experience',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='staff/images/'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='qualification',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
