# Generated by Django 4.2.9 on 2024-02-14 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0005_remove_staffdetails_join_data_staffdetails_join_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdetails',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='experience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
