# Generated by Django 4.2.9 on 2024-02-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0006_staffdetails_age_alter_staffdetails_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='experience',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='image',
            field=models.ImageField(null=True, upload_to='staff/images/'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='nationality',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='qualification',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
